import type { Metadata } from 'next';
import './globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({
	subsets: ['latin'], // you can add more subsets if needed
	variable: '--font-inter', // optional: for Tailwind usage
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'ffff',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body suppressHydrationWarning className={`${inter.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
